clients:
  coinmarketcap:
    apiKey: change-me
  etherscan:
    apiKey: change-me
  nftport:
    apiKey: change-me

databases:
  pg:
    address: 127.0.0.1:26257
    database: defaultdb
    debug: true
    password: ""
    user: root

http:
  port: ${PORT:9080}

logging:
  driver: dev
  level: info
