name: Continues Delivery
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Deploy - currency http
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        branch: main
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: trenddapp-backend-currency-http
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        procfile: "web: bin/currency serve http"
        region: eu
      env:
        HD_CONFIG: ${{secrets.CONFIG}}
        HD_GOVERSION: go1.18
    - name: Deploy - nft http
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        branch: main
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: trenddapp-backend-nft-http
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        procfile: "web: bin/nft serve http"
        region: eu
      env:
        HD_CONFIG: ${{secrets.CONFIG}}
        HD_GOVERSION: go1.18
