name: Continues Integration
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
